// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sswwuosrireyfhcqvgpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzd3d1b3NyaXJleWZoY3F2Z3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwODUyODAsImV4cCI6MjA1MzY2MTI4MH0.G3dGuYSosm-9fOTP-9QCK2H6nAY-KjndcdNoOGXI1dI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);